server:
  port: 8085
  shutdown: graceful

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    registry-fetch-interval-seconds: 5
    
swagger:
  ui-path: /swagger-ui.html
  api-docs: /v3/api-docs

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  flyway:
    enabled: true
    table: flyway_schema_history_user
    locations: classpath:db/migration
    baseline-on-migrate: false
  thymeleaf:
    prefix: classpath:/templates/mail/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB
    
management:
  endpoints:
    web:
      exposure:
        include: health, info

smtp:
  from: Trend <no-reply@trendapp.uk>
