server:
  port: 8085

swagger:
  ui-path: /swagger-ui.html
  api-docs: /v3/api-docs

spring:
  flyway:
    enabled: true
    table: flyway_schema_history_user
    locations: classpath:db/migration
    baseline-on-migrate: false
  thymeleaf:
    prefix: classpath:/templates/mail/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB
    
management:
  endpoints:
    web:
      exposure:
        include: health, info
