server:
  port: 8084

swagger:
  ui-path: /swagger-ui.html
  api-docs: /v3/api-docs

spring:
  flyway:
    enabled: true
    table: flyway_schema_history_user
    locations: classpath:db/migration
    baseline-on-migrate: false
    
management:
  endpoints:
    web:
      exposure:
        include: health, info
