server:
  port: 8084
  shutdown: graceful

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    registry-fetch-interval-seconds: 5
    
swagger:
  ui-path: /swagger-ui.html
  api-docs: /v3/api-docs

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  flyway:
    enabled: true
    table: flyway_schema_history_user
    locations: classpath:db/migration
    baseline-on-migrate: false
  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB
    
management:
  endpoints:
    web:
      exposure:
        include: health, info

maxSize:
  mb:
    oneToOneChat: 50
    oneToOneChatErrorMsg: The uploaded image exceeds the maximum allowed size of 50 MB. Please upload an image within the size limit.
    globalGroupChat: 2000
    globalGroupChatErrorMsg: The uploaded image exceeds the maximum allowed size of 2 GB. Please upload an image within the size limit.  
    post: 1000
    postErrorMsg: The uploaded image exceeds the maximum allowed size of 1 GB. Please upload an image within the size limit.
    userProfile: 50
    userProfileErrorMsg: The uploaded image exceeds the maximum allowed size of 50 MB. Please upload an image within the size limit.  
    clip: 1000
    clipErrorMsg: The uploaded video exceeds the maximum allowed size of 1 GB. Please upload an video within the size limit.    
    clipCover: 50
    clipCoverErrorMsg: The uploaded cover image exceeds the maximum allowed size of 50 MB. Please upload an image within the size limit.
    postCover: 50
    postCoverErrorMsg: The uploaded file exceeds the maximum allowed size of 50 MB. Please upload an image within the size limit.
    commonPostCommentCover: 50
    commonPostCommentCoverErrorMsg: The uploaded file exceeds the maximum allowed size of 50 MB. Please upload an image within the size limit.
    commonPostComment: 50
    commonPostCommentErrorMsg: The uploaded file exceeds the maximum allowed size of 50 MB. Please upload an image within the size limit.
    groupImage: 50
    groupImageErrorMsg: The uploaded file exceeds the maximum allowed size of 50 MB. Please upload an image within the size limit.
    groupMessage: 1000
    groupMessageErrorMsg: The uploaded video exceeds the maximum allowed size of 1 GB. Please upload an video within the size limit.
