server:
  forward-headers-strategy: framework 

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    secure-port-enabled: true
    # Use the variable or hardcode the IP directly
    status-page-url: https://18.175.102.205
    health-check-url: https://18.175.102.205
 
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - name: JwtAuthenticationFilter
          args:
            secret: ofz8Tz+1GJEJ5efPxvqkTACLqdIGUoreFguLAixE/KI=
            enableLogging: true
            publicPaths:
              - /auth
              - /auth/**
              - /swagger-ui/**
              - /v3/api-docs/**
  redis:
    host: localhost
    port: 6379

app:
  config-source: this is gateway-service-home.yml
