server:
  base-url: ${HR_APP_BASE_URL}

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    
spring:
  datasource:
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:5433}   # ✅ Add this line
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Test@123}
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/acadafix
    hikari:
      maximum-pool-size: 2
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        batch_versioned_data: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}           # 1 hour
  refresh-expiration: ${JWT_REFRESH_EXPIRATION} # 30 days
  remember-expiration: ${JWT_REMEMBER_EXPIRATION} # 7 days

logging:
  level:
    # Keep Flyway migration logs in DEBUG (optional, useful for DB migrations)
    org.flywaydb.core: DEBUG

    # Suppress all Apache HTTP client debug logs
    org.apache.hc.client5.http: WARN
    org.apache.hc.core5.http: WARN

    # Suppress Eureka / Netflix Discovery verbose logs
    com.netflix.discovery: WARN

    # Suppress Spring RestTemplate HTTP DEBUG logs
    org.springframework.web.client.RestTemplate: WARN

    # Suppress Hikari connection pool debug logs
    com.zaxxer.hikari: WARN

    # Keep your own application logs at INFO
    com.acadafix: INFO

    # Suppress Spring framework debug logs
    org.springframework: INFO

app:
  oauth2:
    base-url: ${HR_APP_BASE_URL}
  sso:
    error-page-url: ${SSO_ERROR_PAGE_URL}
    token-expiry-minutes: ${SSO_TOKEN_EXPIRY_MINUES:2}
  config-source: this is hr-service-home.yml
  
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

aws:
  s3:
    bucket: ${AWS_S3_BUCKET:acadafix-bucket-london}
    region: ${AWS_S3_REGION:eu-west-2}
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}

connect:
  new-connections:
    match:
      expiry:
        days: 10
      expiring-soon:
        day: 9
